### PR TITLE
add blur sigma parameter to boundarybackgroundparams

### PR DESCRIPTION
**Pull request by tksuns12**
If blurring the boundary background is possible, making glassmorphic design will be much easier to implement in this awesome package!!

### CODE REVIEW

**Comment by alnitak** [comment]
Hi and thanks for your PR!
There is [BackgroundParams](https://github.com/alnitak/flutter_star_menu#backgroundparams) where you can set the background blur and color, you can also tell to use an animation transition for both of them.

**Comment by tksuns12** [comment]
I know there is BackgroundParams but it blurred the whole background of the screen but what I intended to do was just to blur the container in which items are listed linearly.

**Comment by alnitak** [comment]
Hi @tksuns12, 
sorry for this long awaiting!!! I forgot this!! Maybe I was very busy at that time :(
I like your PR, I merged it.

Thank you

**Comment by tksuns12** [comment]
@alnitak Thank you very much!!

**Pull request merged**
